# Generated by Django 4.2.2 on 2023-06-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
    ]
